[versions]
#jetbrains
kotlin = "1.9.25"
#Detekt
detekt = "1.23.3"
#AndroidX
androidx-print = "1.0.0"
#Fossify
commons = "8038e3277e"
#Gradle
gradlePlugins-agp = "8.7.3"
#build
app-build-compileSDKVersion = "34"
app-build-targetSDK = "34"
app-build-minimumSDK = "26"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
#versioning
app-version-appId = "org.fossify.paint"
app-version-versionCode = "1"
app-version-versionName = "1.0.0"
[libraries]
#AndroidX
androidx-print = { module = "androidx.print:print", version.ref = "androidx-print" }
#Fossify
fossify-commons = { module = "org.fossify:commons", version.ref = "commons" }
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
